### ISSUE TITLE
can't run for some native error

### ISSUE THREAD

**Issue by laogui** [alantoa/react-native-lottie-tabbar#1]
it's show error: `com.facebook.react.bridge.JSApplicationIllegalArgumentException: Animated node with ID 2 already exists`

react-native-reanimated is  latest version 2.4.1

---

Another issue，animted-tab-bar-item.tsx first line path is error: 
`import { palette } from '../example/src/App';`

**Comment by alantoa** [comment]
@laogui Hi, I fixed, you can try again!
Call me if you have any questions!
